<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\M365Trace.Core\M365Trace.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\SessionClassification.json" />
    <EmbeddedResource Include="Data\RulesetStrings.json" />
    <EmbeddedResource Include="Data\RulesetManifest.json" />
  </ItemGroup>

</Project>
